# This is a basic workflow to help you get started with Actions

name: lnr

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  submit_report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python3 report.py -u ${{ secrets.USER_NAME }} -p ${{ secrets.USER_PASS }} 
