# This is a basic workflow to help you get started with Actions

name: lnr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  submit_report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      env: # Or as an environment variable
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASS: ${{ secrets.USER_PASS }}
      run: |
        python3 main.py -u $USER_NAME -p $USER_PASS
      
